### ISSUE TITLE
初始化出错导致 footer 无法点击

### ISSUE THREAD

**Issue by Tsuk1ko** [itorr/world-ex#4]
![image](https://user-images.githubusercontent.com/24877906/196600490-b773eaec-b927-4bcb-b74d-8da42e8a0e28.png)

![image](https://user-images.githubusercontent.com/24877906/196600515-2ad6a7d4-caed-4155-ae46-e658f418879e.png)

**Comment by itorr** [comment]
原来是这个原因导致的 bug 感谢反馈，尝试修复了ヽ(･ω･´ﾒ)

**Comment by Tsuk1ko** [comment]
好快，感谢修复！
