### ISSUE TITLE
夏威夷独立了？

### ISSUE THREAD

**Issue by cczhong11** [itorr/world-ex#6]
夏威夷属于美国所以不是两个国家。
<img width="724" alt="image" src="https://user-images.githubusercontent.com/7358252/196774691-aeaf7d84-f92d-4acb-b001-8a7b5785d130.png">

**Comment by itorr** [comment]
https://github.com/itorr/world-ex/blob/01d1a01d778c165b56d03f27614ec165059807f3/README.md?plain=1#L7
